# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brick' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Brick
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'SnapKit'

  target 'BrickTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrickUITests' do
    # Pods for testing
  end

end
